INSERT INTO Car (brand, type) values ('BMW','118d');
INSERT INTO Car (brand, type) values ('BMW','120d');
INSERT INTO Car (brand, type) values ('BMW','220d');
INSERT INTO Car (brand, type) values ('BMW','318d');
INSERT INTO Car (brand, type) values ('BMW','320d');
INSERT INTO Car (brand, type) values ('BMW','335i');
INSERT INTO Car (brand, type) values ('BMW','420d');
INSERT INTO Car (brand, type) values ('BMW','520d');
INSERT INTO Car (brand, type) values ('BMW','635i');
INSERT INTO Car (brand, type) values ('BMW','730d');
INSERT INTO Car (brand, type) values ('BMW','M1');
INSERT INTO Car (brand, type) values ('BMW','M2');
INSERT INTO Car (brand, type) values ('BMW','M3');
INSERT INTO Car (brand, type) values ('BMW','M4');
INSERT INTO Car (brand, type) values ('BMW','M5');
INSERT INTO Car (brand, type) values ('BMW','M6');
INSERT INTO Car (brand, type) values ('Audi','A1');
INSERT INTO Car (brand, type) values ('Audi','A3');
INSERT INTO Car (brand, type) values ('Audi','A4');
INSERT INTO Car (brand, type) values ('Audi','A5');
INSERT INTO Car (brand, type) values ('Audi','A6');
INSERT INTO Car (brand, type) values ('Audi','A7');
INSERT INTO Car (brand, type) values ('Audi','A8');
INSERT INTO Car (brand, type) values ('Audi','S3');
INSERT INTO Car (brand, type) values ('Audi','S4');
INSERT INTO Car (brand, type) values ('Audi','S5');
INSERT INTO Car (brand, type) values ('Audi','S6');
INSERT INTO Car (brand, type) values ('Audi','RS3');
INSERT INTO Car (brand, type) values ('Audi','RS4');
INSERT INTO Car (brand, type) values ('Audi','RS5');
INSERT INTO Car (brand, type) values ('Audi','RS6');
INSERT INTO Car (brand, type) values ('Audi','Q3');
INSERT INTO Car (brand, type) values ('Audi','Q5');
INSERT INTO Car (brand, type) values ('Audi','Q7');
INSERT INTO Car (brand, type) values ('Volkswagen','Jetta');
INSERT INTO Car (brand, type) values ('Volkswagen','Passat');
INSERT INTO Car (brand, type) values ('Volkswagen','CC');
INSERT INTO Car (brand, type) values ('Volkswagen','Golf SportWagen');
INSERT INTO Car (brand, type) values ('Volkswagen','Tiguan');
INSERT INTO Car (brand, type) values ('Volkswagen','Touareg');
INSERT INTO Car (brand, type) values ('Volkswagen','Beetle');
INSERT INTO Car (brand, type) values ('Volkswagen','Golf');
INSERT INTO Car (brand, type) values ('Volkswagen','Golf GTI');
INSERT INTO Car (brand, type) values ('Volkswagen','e-Golf');
INSERT INTO Car (brand, type) values ('Volkswagen','Golf R');
INSERT INTO Car (brand, type) values ('Volkswagen','Beetle Convertible');
